// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khwzzdoonlthwopmssmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtod3p6ZG9vbmx0aHdvcG1zc21tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDM3NTgsImV4cCI6MjA1NTYxOTc1OH0.vit0p8ldn7G62hqQPxKu0TNTrPrFEzuc1468wbfUNpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);